GET http://localhost:3001/api/blogs

###

GET http://localhost:3001/api/blogs/61d4785391d0997da49365d0

###

POST http://localhost:3001/api/blogs 
Content-Type: application/json

{
    "title": "Game of Death",
  "author": "Brian volt",
  "url": "Not on internet",
  "likes": "134"
}

###

DELETE http://localhost:3001/api/blogs/61d87234d90f3b3073d0efe0