GET http://localhost:3003/api/blogs 

###

POST http://localhost:3003/api/blogs 
Content-Type: application/json

{
    "title": "Game of survival",
  "author": "Brian volt",
  "url": "Not on internet",
  "likes": "134"
}