GET http://localhost:3003/api/blogs 

###

POST http://localhost:3003/api/blogs 
Content-Type: application/json

{
    "title": "The far from the north",
  "author": "Steven purple",
  "url": "Not on internet",
  "likes": "1234"
}